### PR TITLE
Mdspell

### PR DESCRIPTION
**Pull request by kmadel**

### CODE REVIEW

**Comment by kmadel** [comment]
@logandonley I installed the Spell Right plugin into VS Code (and the Write Good plugin) - so that may be a better way than have those be part of the Jenkins X job.

**Comment by logandonley** [comment]
> @logandonley I installed the Spell Right plugin into VS Code (and the Write Good plugin) - so that may be a better way than have those be part of the Jenkins X job.

@kmadel I think you might be right. I've been looking into getting the output into the github comments and it seems like the most straightforward path would be just running a rest call to github and trying to pull the credentials from the `jx steps git credentials` output file. 

This would mean creating at least 1, maybe several custom images with the api calls built in alongside the write-good/mdspell tools. Should be doable, but that adds more to maintain.

The VS Code plugin could be a good solution. Also maybe a pre-commit hook which runs those tools on each commit could be another solution.

**Pull request closed without merging**
